export const FETCH_STATS_BY_DATE = 'FETCH_STATS_BY_DATE';
export const FETCH_STATS_BY_DATE_SUCCESS = 'FETCH_STATS_BY_DATE_SUCCESS';
export const FETCH_STATS_BY_DATE_FAILURE = 'FETCH_STATS_BY_DATE_FAILURE';
export const FETCH_DFS_FOR_RESEARCH = 'FETCH_DFS_FOR_RESEARCH';
export const FETCH_DFS_FOR_RESEARCH_SUCCESS = 'FETCH_DFS_FOR_RESEARCH_SUCCESS';
export const FETCH_DFS_FOR_RESEARCH_FAILURE = 'FETCH_DFS_FOR_RESEARCH_FAILURE';
export const FETCH_TEAM_HISTORY = 'FETCH_TEAM_HISTORY';
export const FETCH_TEAM_HISTORY_SUCCESS = 'FETCH_TEAM_HISTORY_SUCCESS';
export const FETCH_TEAM_HISTORY_FAILURE = 'FETCH_TEAM_HISTORY_FAILURE';
export const SCRAPE_STATS = 'SCRAPE_STATS';
export const SCRAPE_STATS_SUCCESS = 'SCRAPE_STATS_SUCCESS';
export const SCRAPE_STATS_FAILURE = 'SCRAPE_STATS_FAILURE';
export const FETCH_SCOREBOARD = 'FETCH_SCOREBOARD';
export const FETCH_SCOREBOARD_SUCCESS = 'FETCH_SCOREBOARD_SUCCESS';
export const FETCH_SCOREBOARD_FAILURE = 'FETCH_SCOREBOARD_FAILURE';
export const FETCH_SCORE_TREND = 'FETCH_SCORE_TREND';
export const FETCH_SCORE_TREND_SUCCESS = 'FETCH_SCORE_TREND_SUCCESS';
export const FETCH_SCORE_TREND_FAILURE = 'FETCH_SCORE_TREND_FAILURE';
export const FETCH_TEAM_LOGS = 'FETCH_TEAM_LOGS';
export const FETCH_TEAM_LOGS_SUCCESS = 'FETCH_TEAM_LOGS_SUCCESS';
export const FETCH_TEAM_LOGS_FAILURE = 'FETCH_TEAM_LOGS_FAILURE';

export const FETCH_PLAYER_LOGS = 'FETCH_PLAYER_LOGS';
export const FETCH_PLAYER_LOGS_SUCCESS = 'FETCH_PLAYER_LOGS_SUCCESS';
export const FETCH_PLAYER_LOGS_FAILURE = 'FETCH_PLAYER_LOGS_FAILURE';
export const FETCH_HITTER_LOGS = 'FETCH_HITTER_LOGS';
export const FETCH_HITTER_LOGS_SUCCESS = 'FETCH_HITTER_LOGS_SUCCESS';
export const FETCH_HITTER_LOGS_FAILURE = 'FETCH_HITTER_LOGS_FAILURE';
export const FETCH_PITCHER_LOGS = 'FETCH_PITCHER_LOGS';
export const FETCH_PITCHER_LOGS_SUCCESS = 'FETCH_PITCHER_LOGS_SUCCESS';
export const FETCH_PITCHER_LOGS_FAILURE = 'FETCH_PITCHER_LOGS_FAILURE';

export const FETCH_CUMULATIVE_PLAYER_STATS = 'FETCH_CUMULATIVE_PLAYER_STATS';
export const FETCH_CUMULATIVE_PLAYER_STATS_SUCCESS = 'FETCH_CUMULATIVE_PLAYER_STATS_SUCCESS';
export const FETCH_CUMULATIVE_PLAYER_STATS_FAILURE = 'FETCH_CUMULATIVE_PLAYER_STATS_FAILURE';
export const FETCH_ALL_CUMULATIVE_PLAYER_STATS = 'FETCH_ALL_CUMULATIVE_PLAYER_STATS';
export const FETCH_ALL_CUMULATIVE_PLAYER_STATS_SUCCESS = 'FETCH_ALL_CUMULATIVE_PLAYER_STATS_SUCCESS';
export const FETCH_ALL_CUMULATIVE_PLAYER_STATS_FAILURE = 'FETCH_ALL_CUMULATIVE_PLAYER_STATS_FAILURE';

export const FETCH_DAILY_STATS = 'FETCH_DAILY_STATS';
export const FETCH_DAILY_STATS_SUCCESS = 'FETCH_DAILY_STATS_SUCCESS';
export const FETCH_DAILY_STATS_FAILURE = 'FETCH_DAILY_STATS_FAILURE';

export const SET_FEED_FILTER = 'SET_FEED_FILTER';
export const SET_SALARY_FILTER_MIN = 'SET_SALARY_FILTER_MIN';
export const SET_SALARY_FILTER_MAX = 'SET_SALARY_FILTER_MAX';
export const SET_POSITION_FILTER = 'SET_POSITION_FILTER';
export const SET_TEAM_FILTER = 'SET_TEAM_FILTER';

export const LINEUP_PLAYER_ADD = 'LINEUP_PLAYER_ADD';
export const LINEUP_PLAYER_REMOVE = 'LINEUP_PLAYER_REMOVE';
export const LINEUP_CLEAR = 'LINEUP_CLEAR';

export const FETCH_BOXSCORE = 'FETCH_BOXSCORE';
export const FETCH_BOXSCORE_SUCCESS = 'FETCH_BOXSCORE_SUCCESS';
export const FETCH_BOXSCORE_FAILURE = 'FETCH_BOXSCORE_FAILURE';

export const FETCH_PLAYBYPLAY = 'FETCH_PLAYBYPLAY';
export const FETCH_PLAYBYPLAY_SUCCESS = 'FETCH_PLAYBYPLAY_SUCCESS';
export const FETCH_PLAYBYPLAY_FAILURE = 'FETCH_PLAYBYPLAY_FAILURE';

export const FETCH_STARTING_LINEUP = 'FETCH_STARTING_LINEUP';
export const FETCH_STARTING_LINEUP_SUCCESS = 'FETCH_STARTING_LINEUP_SUCCESS';
export const FETCH_STARTING_LINEUP_FAILURE = 'FETCH_STARTING_LINEUP_FAILURE';

export const FETCH_DIVISION_STANDINGS = 'FETCH_DIVISION_STANDINGS';
export const FETCH_DIVISION_STANDINGS_SUCCESS = 'FETCH_DIVISION_STANDINGS_SUCCESS';
export const FETCH_DIVISION_STANDINGS_FAILURE = 'FETCH_DIVISION_STANDINGS_FAILURE';

export const SET_DATE = 'SET_DATE';
