export const HITTER_CATEGORIES = {
  GamesPlayed: 'Highlights',
  Homeruns: 'Highlights',
  Runs: 'Highlights',
  RunsBattedIn: 'Highlights',
  StolenBases: 'Highlights',
  BattingAvg: 'Highlights',
  BatterOnBasePlusSluggingPct: 'Highlights',
  BatterSwings: 'Hitting',
  PitchesFaced: 'Hitting',
  PlateAppearances: 'Hitting',
  Hits: 'Hitting',
  HitByPitch: 'Hitting',
  BatterStrikesMiss: 'Hitting',
  BatterStrikesLooking: 'Hitting',
  FieldingPct: 'Fielding',
  RangeFactor: 'Fielding',
  Errors: 'Fielding',
};
